### Merging my booktok merged list AND the kindle list to create BI visuals...

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [4]:
booktok_on_kindle = pd.read_csv(r"C:\Users\jenni\OneDrive\Desktop\DA12\Projects\Goodreads_Kindle_NSScapstone\data\CLEANED\booktok_on_kindle.csv")

In [6]:
kindle = pd.read_csv(r"C:\Users\jenni\OneDrive\Desktop\DA12\Projects\Goodreads_Kindle_NSScapstone\data\CLEANED\final_kindle_books.csv")

In [8]:
booktok_on_kindle['Booktok'] = 'Y'

In [10]:
kindle['Booktok'] = 'N'

In [12]:
merged_all = pd.merge(booktok_on_kindle, kindle, on='key', how='outer')
merged_all.head()

,key,Title,Author,Kindle Price_x,Goodreads Avg Rating,Kindle Avg Rating_x,Number of Goodreads Ratings,Number of Kindle Reviews_x,Num_shelved_booktok,Goodreads Top Genre,...,Amazon URL_y,Kindle Avg Rating_y,Number of Kindle Reviews_y,Kindle Price_y,isKindleUnlimited_y,isBestSeller_y,isEditorsPick_y,isGoodReadsChoice_y,category_name_y,Booktok_y
0,"""a""isforalibisuegrafton",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,https://www.amazon.com/dp/B002HHPVBC,4.1,0,9.99,True,False,False,False,"Mystery, Thriller & Suspense",N
1,"""agiftfromthestars""kindleeditionelenadanaan",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,https://www.amazon.com/dp/B0963WTLJ5,4.5,0,4.99,False,False,False,False,Science & Math,N
2,"""alltherealindiansdiedoff""roxannedunbar-ortiz",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,https://www.amazon.com/dp/B01AEPR4CM,4.7,358,12.99,False,False,False,False,Politics & Social Sciences,N
3,"""anamericanband,theamericastory""danpeek",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,https://www.amazon.com/dp/B004VTGVFE,4.3,237,8.49,False,False,False,False,Arts & Photo graphy,N
4,"""aproblemfromhell""samanthapower",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,https://www.amazon.com/dp/B00D7MSXQQ,4.6,877,15.99,False,False,False,False,Politics & Social Sciences,N

In [14]:
merged_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125435 entries, 0 to 125434
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   key                          125044 non-null  object
 1   Title                        1018 non-null    object
 2   Author                       1018 non-null    object
 3   Kindle Price_x               1018 non-null    float64
 4   Goodreads Avg Rating         1018 non-null    float64
 5   Kindle Avg Rating_x          1018 non-null    float64
 6   Number of Goodreads Ratings  1018 non-null    object
 7   Number of Kindle Reviews_x   1018 non-null    float64
 8   Num_shelved_booktok          1018 non-null    float64
 9   Goodreads Top Genre          1012 non-null    object
 10  category_name_x              1018 non-null    object
 11  year_published               993 non-null     float64
 12  Number of Pages              1010 non-null    object
 13  isKindleUnlimited_x          1018 non-null    object
 14  isBestSeller_x               1018 non-null    object
 15  isEditorsPick_x              1018 non-null    object
 16  isGoodReadsChoice_x          1018 non-null    object
 17  Goodreads URL                1018 non-null    object
 18  Amazon URL_x                 1018 non-null    object
 19  Image URL                    1018 non-null    object
 20  Booktok_x                    1018 non-null    object
 21  title                        125435 non-null  object
 22  author                       125044 non-null  object
 23  Amazon URL_y                 125435 non-null  object
 24  Kindle Avg Rating_y          125435 non-null  float64
 25  Number of Kindle Reviews_y   125435 non-null  int64
 26  Kindle Price_y               125435 non-null  float64
 27  isKindleUnlimited_y          125435 non-null  bool
 28  isBestSeller_y               125435 non-null  bool
 29  isEditorsPick_y              125435 non-null  bool
 30  isGoodReadsChoice_y          125435 non-null  bool
 31  category_name_y              125435 non-null  object
 32  Booktok_y                    125435 non-null  object
dtypes: bool(4), float64(8), int64(1), object(20)
memory usage: 28.2+ MB

In [16]:
merged_all['Booktok_x'] = merged_all['Booktok_x'].fillna(merged_all['Booktok_y'])
merged_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125435 entries, 0 to 125434
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   key                          125044 non-null  object
 1   Title                        1018 non-null    object
 2   Author                       1018 non-null    object
 3   Kindle Price_x               1018 non-null    float64
 4   Goodreads Avg Rating         1018 non-null    float64
 5   Kindle Avg Rating_x          1018 non-null    float64
 6   Number of Goodreads Ratings  1018 non-null    object
 7   Number of Kindle Reviews_x   1018 non-null    float64
 8   Num_shelved_booktok          1018 non-null    float64
 9   Goodreads Top Genre          1012 non-null    object
 10  category_name_x              1018 non-null    object
 11  year_published               993 non-null     float64
 12  Number of Pages              1010 non-null    object
 13  isKindleUnlimited_x          1018 non-null    object
 14  isBestSeller_x               1018 non-null    object
 15  isEditorsPick_x              1018 non-null    object
 16  isGoodReadsChoice_x          1018 non-null    object
 17  Goodreads URL                1018 non-null    object
 18  Amazon URL_x                 1018 non-null    object
 19  Image URL                    1018 non-null    object
 20  Booktok_x                    125435 non-null  object
 21  title                        125435 non-null  object
 22  author                       125044 non-null  object
 23  Amazon URL_y                 125435 non-null  object
 24  Kindle Avg Rating_y          125435 non-null  float64
 25  Number of Kindle Reviews_y   125435 non-null  int64
 26  Kindle Price_y               125435 non-null  float64
 27  isKindleUnlimited_y          125435 non-null  bool
 28  isBestSeller_y               125435 non-null  bool
 29  isEditorsPick_y              125435 non-null  bool
 30  isGoodReadsChoice_y          125435 non-null  bool
 31  category_name_y              125435 non-null  object
 32  Booktok_y                    125435 non-null  object
dtypes: bool(4), float64(8), int64(1), object(20)
memory usage: 28.2+ MB

In [18]:
merged_all.loc[124433]

key                                                        yourstrulyabbyjimenez
Title                                                                Yours Truly
Author                                                              Abby Jimenez
Kindle Price_x                                                             10.99
Goodreads Avg Rating                                                        4.32
Kindle Avg Rating_x                                                          4.5
Number of Goodreads Ratings                                             479,830
Number of Kindle Reviews_x                                               11389.0
Num_shelved_booktok                                                         65.0
Goodreads Top Genre                                                      Romance
category_name_x                                             Literature & Fiction
year_published                                                            2023.0
Number of Pages                                                        416 pages
isKindleUnlimited_x                                                        False
isBestSeller_x                                                             False
isEditorsPick_x                                                             True
isGoodReadsChoice_x                                                        False
Goodreads URL                  https://www.goodreads.com/book/show/61918816-y...
Amazon URL_x                                https://www.amazon.com/dp/B0B8YVRMW4
Image URL                      https://i.gr-assets.com/images/S/compressed.ph...
Booktok_x                                                                      Y
title                                                                Yours Truly
author                                                              Abby Jimenez
Amazon URL_y                                https://www.amazon.com/dp/B0B8YVRMW4
Kindle Avg Rating_y                                                          4.5
Number of Kindle Reviews_y                                                 11389
Kindle Price_y                                                             10.99
isKindleUnlimited_y                                                        False
isBestSeller_y                                                             False
isEditorsPick_y                                                             True
isGoodReadsChoice_y                                                        False
category_name_y                                             Literature & Fiction
Booktok_y                                                                      N
Name: 124433, dtype: object

In [20]:
unique_count = merged_all['Booktok_x'].nunique()

In [22]:
print(f"The number of unique values in 'Booktok_x' is: {unique_count}")

The number of unique values in 'Booktok_x' is: 2

In [24]:
merged_all = merged_all.drop(['Title', 'Author', 'Kindle Price_x', 'Kindle Avg Rating_x', 'Number of Kindle Reviews_x', 'category_name_x', 'isKindleUnlimited_x', 'isBestSeller_x', 'isEditorsPick_x', 'isGoodReadsChoice_x', 'Amazon URL_x'], axis=1)
merged_all.head()

,key,Goodreads Avg Rating,Number of Goodreads Ratings,Num_shelved_booktok,Goodreads Top Genre,year_published,Number of Pages,Goodreads URL,Image URL,Booktok_x,...,Amazon URL_y,Kindle Avg Rating_y,Number of Kindle Reviews_y,Kindle Price_y,isKindleUnlimited_y,isBestSeller_y,isEditorsPick_y,isGoodReadsChoice_y,category_name_y,Booktok_y
0,"""a""isforalibisuegrafton",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,...,https://www.amazon.com/dp/B002HHPVBC,4.1,0,9.99,True,False,False,False,"Mystery, Thriller & Suspense",N
1,"""agiftfromthestars""kindleeditionelenadanaan",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,...,https://www.amazon.com/dp/B0963WTLJ5,4.5,0,4.99,False,False,False,False,Science & Math,N
2,"""alltherealindiansdiedoff""roxannedunbar-ortiz",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,...,https://www.amazon.com/dp/B01AEPR4CM,4.7,358,12.99,False,False,False,False,Politics & Social Sciences,N
3,"""anamericanband,theamericastory""danpeek",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,...,https://www.amazon.com/dp/B004VTGVFE,4.3,237,8.49,False,False,False,False,Arts & Photo graphy,N
4,"""aproblemfromhell""samanthapower",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,...,https://www.amazon.com/dp/B00D7MSXQQ,4.6,877,15.99,False,False,False,False,Politics & Social Sciences,N

In [28]:
merged_all.loc[124433]

key                                                        yourstrulyabbyjimenez
Goodreads Avg Rating                                                        4.32
Number of Goodreads Ratings                                             479,830
Num_shelved_booktok                                                         65.0
Goodreads Top Genre                                                      Romance
year_published                                                            2023.0
Number of Pages                                                        416 pages
Goodreads URL                  https://www.goodreads.com/book/show/61918816-y...
Image URL                      https://i.gr-assets.com/images/S/compressed.ph...
Booktok_x                                                                      Y
title                                                                Yours Truly
author                                                              Abby Jimenez
Amazon URL_y                                https://www.amazon.com/dp/B0B8YVRMW4
Kindle Avg Rating_y                                                          4.5
Number of Kindle Reviews_y                                                 11389
Kindle Price_y                                                             10.99
isKindleUnlimited_y                                                        False
isBestSeller_y                                                             False
isEditorsPick_y                                                             True
isGoodReadsChoice_y                                                        False
category_name_y                                             Literature & Fiction
Booktok_y                                                                      N
Name: 124433, dtype: object

In [30]:
merged_all = merged_all.drop(['Booktok_y'], axis=1)
merged_all.head()

,key,Goodreads Avg Rating,Number of Goodreads Ratings,Num_shelved_booktok,Goodreads Top Genre,year_published,Number of Pages,Goodreads URL,Image URL,Booktok_x,...,author,Amazon URL_y,Kindle Avg Rating_y,Number of Kindle Reviews_y,Kindle Price_y,isKindleUnlimited_y,isBestSeller_y,isEditorsPick_y,isGoodReadsChoice_y,category_name_y
0,"""a""isforalibisuegrafton",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,...,Sue Grafton,https://www.amazon.com/dp/B002HHPVBC,4.1,0,9.99,True,False,False,False,"Mystery, Thriller & Suspense"
1,"""agiftfromthestars""kindleeditionelenadanaan",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,...,elena danaan,https://www.amazon.com/dp/B0963WTLJ5,4.5,0,4.99,False,False,False,False,Science & Math
2,"""alltherealindiansdiedoff""roxannedunbar-ortiz",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,...,Roxanne Dunbar-Ortiz,https://www.amazon.com/dp/B01AEPR4CM,4.7,358,12.99,False,False,False,False,Politics & Social Sciences
3,"""anamericanband,theamericastory""danpeek",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,...,Dan Peek,https://www.amazon.com/dp/B004VTGVFE,4.3,237,8.49,False,False,False,False,Arts & Photo graphy
4,"""aproblemfromhell""samanthapower",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,...,Samantha Power,https://www.amazon.com/dp/B00D7MSXQQ,4.6,877,15.99,False,False,False,False,Politics & Social Sciences

In [32]:
merged_all.loc[124433]

key                                                        yourstrulyabbyjimenez
Goodreads Avg Rating                                                        4.32
Number of Goodreads Ratings                                             479,830
Num_shelved_booktok                                                         65.0
Goodreads Top Genre                                                      Romance
year_published                                                            2023.0
Number of Pages                                                        416 pages
Goodreads URL                  https://www.goodreads.com/book/show/61918816-y...
Image URL                      https://i.gr-assets.com/images/S/compressed.ph...
Booktok_x                                                                      Y
title                                                                Yours Truly
author                                                              Abby Jimenez
Amazon URL_y                                https://www.amazon.com/dp/B0B8YVRMW4
Kindle Avg Rating_y                                                          4.5
Number of Kindle Reviews_y                                                 11389
Kindle Price_y                                                             10.99
isKindleUnlimited_y                                                        False
isBestSeller_y                                                             False
isEditorsPick_y                                                             True
isGoodReadsChoice_y                                                        False
category_name_y                                             Literature & Fiction
Name: 124433, dtype: object

In [36]:
merged_all = merged_all[['key', 'title', 'author', 'Booktok_x', 'Kindle Price_y', 'Goodreads Avg Rating', 'Kindle Avg Rating_y', 'Number of Goodreads Ratings', 'Number of Kindle Reviews_y', 'Num_shelved_booktok', 'Goodreads Top Genre', 'category_name_y', 'year_published', 'Number of Pages', 'isKindleUnlimited_y', 'isBestSeller_y', 'isEditorsPick_y', 'isGoodReadsChoice_y', 'Goodreads URL', 'Amazon URL_y', 'Image URL']]
merged_all.head()

,key,title,author,Booktok_x,Kindle Price_y,Goodreads Avg Rating,Kindle Avg Rating_y,Number of Goodreads Ratings,Number of Kindle Reviews_y,Num_shelved_booktok,...,category_name_y,year_published,Number of Pages,isKindleUnlimited_y,isBestSeller_y,isEditorsPick_y,isGoodReadsChoice_y,Goodreads URL,Amazon URL_y,Image URL
0,"""a""isforalibisuegrafton","""A"" is for Alibi",Sue Grafton,N,9.99,NaN,4.1,NaN,0,NaN,...,"Mystery, Thriller & Suspense",NaN,NaN,True,False,False,False,NaN,https://www.amazon.com/dp/B002HHPVBC,NaN
1,"""agiftfromthestars""kindleeditionelenadanaan","""A Gift From The Stars"" Kindle edition",elena danaan,N,4.99,NaN,4.5,NaN,0,NaN,...,Science & Math,NaN,NaN,False,False,False,False,NaN,https://www.amazon.com/dp/B0963WTLJ5,NaN
2,"""alltherealindiansdiedoff""roxannedunbar-ortiz","""All the Real Indians Died Off""",Roxanne Dunbar-Ortiz,N,12.99,NaN,4.7,NaN,358,NaN,...,Politics & Social Sciences,NaN,NaN,False,False,False,False,NaN,https://www.amazon.com/dp/B01AEPR4CM,NaN
3,"""anamericanband,theamericastory""danpeek","""An American Band, The America Story""",Dan Peek,N,8.49,NaN,4.3,NaN,237,NaN,...,Arts & Photo graphy,NaN,NaN,False,False,False,False,NaN,https://www.amazon.com/dp/B004VTGVFE,NaN
4,"""aproblemfromhell""samanthapower","""A Problem from Hell""",Samantha Power,N,15.99,NaN,4.6,NaN,877,NaN,...,Politics & Social Sciences,NaN,NaN,False,False,False,False,NaN,https://www.amazon.com/dp/B00D7MSXQQ,NaN

In [38]:
merged_all.loc[124433]

key                                                        yourstrulyabbyjimenez
title                                                                Yours Truly
author                                                              Abby Jimenez
Booktok_x                                                                      Y
Kindle Price_y                                                             10.99
Goodreads Avg Rating                                                        4.32
Kindle Avg Rating_y                                                          4.5
Number of Goodreads Ratings                                             479,830
Number of Kindle Reviews_y                                                 11389
Num_shelved_booktok                                                         65.0
Goodreads Top Genre                                                      Romance
category_name_y                                             Literature & Fiction
year_published                                                            2023.0
Number of Pages                                                        416 pages
isKindleUnlimited_y                                                        False
isBestSeller_y                                                             False
isEditorsPick_y                                                             True
isGoodReadsChoice_y                                                        False
Goodreads URL                  https://www.goodreads.com/book/show/61918816-y...
Amazon URL_y                                https://www.amazon.com/dp/B0B8YVRMW4
Image URL                      https://i.gr-assets.com/images/S/compressed.ph...
Name: 124433, dtype: object

In [40]:
merged_all = merged_all.rename(columns={
    'Booktok_x': 'isBookTok'
})
merged_all.head()

,key,title,author,isBookTok,Kindle Price_y,Goodreads Avg Rating,Kindle Avg Rating_y,Number of Goodreads Ratings,Number of Kindle Reviews_y,Num_shelved_booktok,...,category_name_y,year_published,Number of Pages,isKindleUnlimited_y,isBestSeller_y,isEditorsPick_y,isGoodReadsChoice_y,Goodreads URL,Amazon URL_y,Image URL
0,"""a""isforalibisuegrafton","""A"" is for Alibi",Sue Grafton,N,9.99,NaN,4.1,NaN,0,NaN,...,"Mystery, Thriller & Suspense",NaN,NaN,True,False,False,False,NaN,https://www.amazon.com/dp/B002HHPVBC,NaN
1,"""agiftfromthestars""kindleeditionelenadanaan","""A Gift From The Stars"" Kindle edition",elena danaan,N,4.99,NaN,4.5,NaN,0,NaN,...,Science & Math,NaN,NaN,False,False,False,False,NaN,https://www.amazon.com/dp/B0963WTLJ5,NaN
2,"""alltherealindiansdiedoff""roxannedunbar-ortiz","""All the Real Indians Died Off""",Roxanne Dunbar-Ortiz,N,12.99,NaN,4.7,NaN,358,NaN,...,Politics & Social Sciences,NaN,NaN,False,False,False,False,NaN,https://www.amazon.com/dp/B01AEPR4CM,NaN
3,"""anamericanband,theamericastory""danpeek","""An American Band, The America Story""",Dan Peek,N,8.49,NaN,4.3,NaN,237,NaN,...,Arts & Photo graphy,NaN,NaN,False,False,False,False,NaN,https://www.amazon.com/dp/B004VTGVFE,NaN
4,"""aproblemfromhell""samanthapower","""A Problem from Hell""",Samantha Power,N,15.99,NaN,4.6,NaN,877,NaN,...,Politics & Social Sciences,NaN,NaN,False,False,False,False,NaN,https://www.amazon.com/dp/B00D7MSXQQ,NaN

In [42]:
merged_all.loc[124433]

key                                                        yourstrulyabbyjimenez
title                                                                Yours Truly
author                                                              Abby Jimenez
isBookTok                                                                      Y
Kindle Price_y                                                             10.99
Goodreads Avg Rating                                                        4.32
Kindle Avg Rating_y                                                          4.5
Number of Goodreads Ratings                                             479,830
Number of Kindle Reviews_y                                                 11389
Num_shelved_booktok                                                         65.0
Goodreads Top Genre                                                      Romance
category_name_y                                             Literature & Fiction
year_published                                                            2023.0
Number of Pages                                                        416 pages
isKindleUnlimited_y                                                        False
isBestSeller_y                                                             False
isEditorsPick_y                                                             True
isGoodReadsChoice_y                                                        False
Goodreads URL                  https://www.goodreads.com/book/show/61918816-y...
Amazon URL_y                                https://www.amazon.com/dp/B0B8YVRMW4
Image URL                      https://i.gr-assets.com/images/S/compressed.ph...
Name: 124433, dtype: object

In [46]:
merged_all.loc[0]

key                                         "a"isforalibisuegrafton
title                                              "A" is for Alibi
author                                                  Sue Grafton
isBookTok                                                         N
Kindle Price_y                                                 9.99
Goodreads Avg Rating                                            NaN
Kindle Avg Rating_y                                             4.1
Number of Goodreads Ratings                                     NaN
Number of Kindle Reviews_y                                        0
Num_shelved_booktok                                             NaN
Goodreads Top Genre                                             NaN
category_name_y                        Mystery, Thriller & Suspense
year_published                                                  NaN
Number of Pages                                                 NaN
isKindleUnlimited_y                                            True
isBestSeller_y                                                False
isEditorsPick_y                                               False
isGoodReadsChoice_y                                           False
Goodreads URL                                                   NaN
Amazon URL_y                   https://www.amazon.com/dp/B002HHPVBC
Image URL                                                       NaN
Name: 0, dtype: object

In [48]:
merged_all.to_csv('merged_all.csv', index=False)